services:
  postgres:
    image: postgres
    container_name: mindfeed_psql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mindfeed 
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mindfeed_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  qdrant:
    image: qdrant/qdrant
    container_name: mindfeed_qdrant
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage  
volumes:
  postgres_data:
  qdrant_data: