name: CI Frontend
on:
  push:
    branches: [main]
    paths-ignore:
      - 'Readme.md'
      - '**/*.md'
      - '.github/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'Readme.md'
      - '**/*.md'
      - '.github/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Frotend dependencies
        run: npm install
        working-directory: ./frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend      